const data = [
    {
        "id": 1,
        "title": "iPhone 9",
        "description": "An apple mobile which is nothing like apple",
        "price": 549,
        "discountPercentage": 12.96,
        "rating": 4.69,
        "stock": 94,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/1/1.jpg", "https://i.dummyjson.com/data/products/1/2.jpg", "https://i.dummyjson.com/data/products/1/3.jpg", "https://i.dummyjson.com/data/products/1/4.jpg", "https://i.dummyjson.com/data/products/1/thumbnail.jpg"]
    }, {
        "id": 2,
        "title": "iPhone X",
        "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
        "price": 899,
        "discountPercentage": 17.94,
        "rating": 4.44,
        "stock": 34,
        "brand": "Apple",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/2/1.jpg", "https://i.dummyjson.com/data/products/2/2.jpg", "https://i.dummyjson.com/data/products/2/3.jpg", "https://i.dummyjson.com/data/products/2/thumbnail.jpg"]
    }, {
        "id": 3,
        "title": "Samsung Universe 9",
        "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
        "price": 1249,
        "discountPercentage": 15.46,
        "rating": 4.09,
        "stock": 36,
        "brand": "Samsung",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/3/1.jpg"]
    }, {
        "id": 4,
        "title": "OPPOF19",
        "description": "OPPO F19 is officially announced on April 2021.",
        "price": 280,
        "discountPercentage": 17.91,
        "rating": 4.3,
        "stock": 123,
        "brand": "OPPO",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/4/1.jpg", "https://i.dummyjson.com/data/products/4/2.jpg", "https://i.dummyjson.com/data/products/4/3.jpg", "https://i.dummyjson.com/data/products/4/4.jpg", "https://i.dummyjson.com/data/products/4/thumbnail.jpg"]
    }, {
        "id": 5,
        "title": "Huawei P30",
        "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
        "price": 499,
        "discountPercentage": 10.58,
        "rating": 4.09,
        "stock": 32,
        "brand": "Huawei",
        "category": "smartphones",
        "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/5/1.jpg", "https://i.dummyjson.com/data/products/5/2.jpg", "https://i.dummyjson.com/data/products/5/3.jpg"]
    }, {
        "id": 6,
        "title": "MacBook Pro",
        "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
        "price": 1749,
        "discountPercentage": 11.02,
        "rating": 4.57,
        "stock": 83,
        "brand": "Apple",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png",
        "images": ["https://i.dummyjson.com/data/products/6/1.png", "https://i.dummyjson.com/data/products/6/2.jpg", "https://i.dummyjson.com/data/products/6/3.png", "https://i.dummyjson.com/data/products/6/4.jpg"]
    }, {
        "id": 7,
        "title": "Galaxy Book",
        "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
        "price": 1499,
        "discountPercentage": 4.15,
        "rating": 4.25,
        "stock": 50,
        "brand": "Samsung",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/7/1.jpg", "https://i.dummyjson.com/data/products/7/2.jpg", "https://i.dummyjson.com/data/products/7/3.jpg", "https://i.dummyjson.com/data/products/7/thumbnail.jpg"]
    }, {
        "id": 8,
        "title": "Surface Laptop 4",
        "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
        "price": 1499,
        "discountPercentage": 10.23,
        "rating": 4.43,
        "stock": 68,
        "brand": "Microsoft",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/8/1.jpg", "https://i.dummyjson.com/data/products/8/2.jpg", "https://i.dummyjson.com/data/products/8/3.jpg", "https://i.dummyjson.com/data/products/8/4.jpg", "https://i.dummyjson.com/data/products/8/thumbnail.jpg"]
    }, {
        "id": 9,
        "title": "Infinix INBOOK",
        "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
        "price": 1099,
        "discountPercentage": 11.83,
        "rating": 4.54,
        "stock": 96,
        "brand": "Infinix",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/9/1.jpg", "https://i.dummyjson.com/data/products/9/2.png", "https://i.dummyjson.com/data/products/9/3.png", "https://i.dummyjson.com/data/products/9/4.jpg", "https://i.dummyjson.com/data/products/9/thumbnail.jpg"]
    }, {
        "id": 10,
        "title": "Pavilion 15-DK1056WM",
        "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
        "price": 1099,
        "discountPercentage": 6.18,
        "rating": 4.43,
        "stock": 89,
        "brand": "HP Pavilion",
        "category": "laptops",
        "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        "images": ["https://i.dummyjson.com/data/products/10/1.jpg", "https://i.dummyjson.com/data/products/10/2.jpg", "https://i.dummyjson.com/data/products/10/3.jpg", "https://i.dummyjson.com/data/products/10/thumbnail.jpeg"]
    }, {
        "id": 11,
        "title": "Half sleeves T shirts",
        "description": "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
        "price": 23,
        "discountPercentage": 12.76,
        "rating": 4.26,
        "stock": 132,
        "brand": "Vintage Apparel",
        "category": "mens-shirts",
        "thumbnail": "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/51/1.png", "https://i.dummyjson.com/data/products/51/2.jpg", "https://i.dummyjson.com/data/products/51/3.jpg", "https://i.dummyjson.com/data/products/51/thumbnail.jpg"]
    }, {
        "id": 12,
        "title": "FREE FIRE T Shirt",
        "description": "quality and professional print - It doesn't just look high quality, it is high quality.",
        "price": 10,
        "discountPercentage": 14.72,
        "rating": 4.52,
        "stock": 128,
        "brand": "FREE FIRE",
        "category": "mens-shirts",
        "thumbnail": "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/52/1.png", "https://i.dummyjson.com/data/products/52/2.png", "https://i.dummyjson.com/data/products/52/3.jpg", "https://i.dummyjson.com/data/products/52/4.jpg", "https://i.dummyjson.com/data/products/52/thumbnail.jpg"]
    }, {
        "id": 13,
        "title": "Printed high quality",
        "description": "Brand: vintage Apparel ,Export quality",
        "price": 35,
        "discountPercentage": 7.54,
        "rating": 4.89,
        "stock": 6,
        "brand": "Vintage Apparel",
        "category": "mens-shirts",
        "thumbnail": "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/53/1.webp", "https://i.dummyjson.com/data/products/53/2.jpg", "https://i.dummyjson.com/data/products/53/3.jpg", "https://i.dummyjson.com/data/products/53/4.jpg", "https://i.dummyjson.com/data/products/53/thumbnail.jpg"]
    }, {
        "id": 14,
        "title": "Pubg Printed Graphic",
        "description": "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
        "price": 46,
        "discountPercentage": 16.44,
        "rating": 4.62,
        "stock": 136,
        "brand": "The Warehouse",
        "category": "mens-shirts",
        "thumbnail": "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/54/1.jpg", "https://i.dummyjson.com/data/products/54/2.jpg", "https://i.dummyjson.com/data/products/54/3.jpg", "https://i.dummyjson.com/data/products/54/4.jpg", "https://i.dummyjson.com/data/products/54/thumbnail.jpg"]
    }, {
        "id": 15,
        "title": "Money Heist Printed",
        "description": "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
        "price": 66,
        "discountPercentage": 15.97,
        "rating": 4.9,
        "stock": 122,
        "brand": "The Warehouse",
        "category": "mens-shirts",
        "thumbnail": "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/55/1.jpg", "https://i.dummyjson.com/data/products/55/2.webp", "https://i.dummyjson.com/data/products/55/3.jpg", "https://i.dummyjson.com/data/products/55/4.jpg", "https://i.dummyjson.com/data/products/55/thumbnail.jpg"]
    }, {
        "id": 16,
        "title": "Leather Straps Wrist",
        "description": "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
        "price": 120,
        "discountPercentage": 7.14,
        "rating": 4.63,
        "stock": 91,
        "brand": "Naviforce",
        "category": "mens-watches",
        "thumbnail": "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/61/1.jpg", "https://i.dummyjson.com/data/products/61/2.png", "https://i.dummyjson.com/data/products/61/3.jpg"]
    }, {
        "id": 17,
        "title": "Waterproof Leather",
        "description": "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
        "price": 46,
        "discountPercentage": 3.15,
        "rating": 4.05,
        "stock": 95,
        "brand": "SKMEI 9117",
        "category": "mens-watches",
        "thumbnail": "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/62/1.jpg", "https://i.dummyjson.com/data/products/62/2.jpg"]
    }, {
        "id": 18,
        "title": "Royal Blue Premium",
        "description": "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
        "price": 50,
        "discountPercentage": 2.56,
        "rating": 4.89,
        "stock": 142,
        "brand": "SKMEI 9117",
        "category": "mens-watches",
        "thumbnail": "https://i.dummyjson.com/data/products/63/thumbnail.webp",
        "images": ["https://i.dummyjson.com/data/products/63/1.jpg", "https://i.dummyjson.com/data/products/63/2.jpg", "https://i.dummyjson.com/data/products/63/3.png", "https://i.dummyjson.com/data/products/63/4.jpeg"]
    }, {
        "id": 19,
        "title": "Leather Strap Skeleton",
        "description": "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
        "price": 46,
        "discountPercentage": 10.2,
        "rating": 4.98,
        "stock": 61,
        "brand": "Strap Skeleton",
        "category": "mens-watches",
        "thumbnail": "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
        "images": ["https://i.dummyjson.com/data/products/64/1.jpg", "https://i.dummyjson.com/data/products/64/2.webp", "https://i.dummyjson.com/data/products/64/3.jpg", "https://i.dummyjson.com/data/products/64/thumbnail.jpg"]
    }, {
        "id": 20,
        "title": "Stainless Steel Wrist",
        "description": "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
        "price": 47,
        "discountPercentage": 17.79,
        "rating": 4.79,
        "stock": 94,
        "brand": "Stainless",
        "category": "mens-watches",
        "thumbnail": "https://i.dummyjson.com/data/products/65/thumbnail.webp",
        "images": ["https://i.dummyjson.com/data/products/65/1.jpg", "https://i.dummyjson.com/data/products/65/2.webp", "https://i.dummyjson.com/data/products/65/3.jpg", "https://i.dummyjson.com/data/products/65/4.webp", "https://i.dummyjson.com/data/products/65/thumbnail.webp"]
    }
];
/*
"total": 25,
"skip": 0,
"limit": 25
}*/
export default data;